title: Introduction to GitHub Apps
tagline: Get started with GitHub Apps in a flash
description: See how automation can improve your workflow and reduce friction with GitHub Apps
template:
  name: introduction-to-github-apps
  url: "https://github.com/githubtraining/introduction-to-github-apps-template.git"
  repo: introduction-to-github-apps-template
before:
  - type: createPullRequest
    title: Introduction to GitHub Apps
    head: intro-gh-apps
    body: 01_intro-gh-apps.md
steps:
  - title: Introduction to GitHub Apps
    description: Learn what a GitHub App is and how to install it
    event: "installation.created"
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: 01_wip-actions.md

  - title: Interacting with the Github App
    description: Once installed, learn how to interact with the app
    event: "pull_request.edited"
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: test
        right: /\b(wip|do not merge|work in progress)\b/i
        else:
          type: respond
          with: 02_WIP-error-message2.md
      - type: respond
        with: 01_defining-webhooks-apis.md

  - title: Getting hooked with webhooks
    description: Understand what webhooks are and how they work
    event: pull_request.edited
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: test
        right: /\b(wip|do not merge|work in progress)\b/i
        else:
          - type: mergePullRequest
            pullRequest: 1 
          - type: createPullRequest
            title: Practice makes perfect
            body: 02_request-info-app-prompt.md
            action_id: new_pr
          - type: respond
            with: 01_merge-success.md
            data:
              url: '%actions.new_pr.data.html_url%'    
      - type: respond
        with: 02_WIP-error-message2.md

  - title: Install Request Info Probot App
    description: There are so many GitHub Apps, let's install another one
    event: installation.created
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: respond
        with: 02_request-info-install-success.md

  - title: Customize your app's response
    description: Learn how to customize the apps default behavior
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: getFileContents
        action_id: fileContents
        filename: config.yml
      - type: gate
        left: "%payload.pull_request.base.ref%"
        operator: "==="
        right: master
        else:
          - type: mergePullRequest
            pullRequest: 2
          - type: createIssue
            title: Congratulations!
            body: 03_graceful-exit.md
            action_id: last_issue
          - type: respond
            with: 02_change-config-success.md
            data:
              url: '%actions.last_issue.data.html_url%'
      - type: respond
        with: make-changes.md
