title: Introduction to GitHub Apps
tagline: Get started with GitHub Apps in a flash
description: See how automation can improve your workflow and reduce friction with GitHub Apps
template:
  name: introduction-to-github-apps-template
  url: "https://github.com/githubtraining/introduction-to-github-apps-template.git"
  repo: introduction-to-github-apps-template
before:
  - type: createIssue
    title: Introduction to GitHub Apps
    body: 01_intro-gh-apps.md 
steps:
  - title: Introduce yourself
    description: Leave a comment with your favorite GitHub App
    event: "issue_comment.created"
    link: {{ repoUrl }}/issues/1
    actions:
      - type: respond
        with: 01_first-class-actor.md
        data:
          url: '%actions.issue.data.html_url%'
          
  - title: Take ownership of the issue 
    description: Assign the issue to yourself
    event: "issues.assigned"
    link: {{ repoUrl }}/issues/1
    actions:
      - type: gate
        left: "%payload.assignee.login%"
        operator: "==="
        right: "%user.username%"
      - type: respond
        with: "01_anatomy-github-app.md"
        
  - title: Anatomy of a GitHub App
    description: Understand the anatomy of a GitHub App
    event: "issues.closed"
    link: {{ repoUrl }}/issues/1
    actions:
      - type: createPullRequest
        title: Introduction to Probot
        body: 02_wip-app-prompt.md
        action_id: new_pr
      - type: respond
        with: 01_close-issue-1.md
        data: 
          url: '%actions.new_pr.data.html_url%'
   
  - title: Install a GitHub Probot App
    description: Learn how to install a GitHub Probot App
    event: installation.created
    link: {{ repoUrl }}/pull/1
    actions:
      - type: respond
        with: 02_wip-success.md
      - type: respond
        with: 02_wip-install-success.md
 
  - title: Interacting with the "WIP" Probot App
    description: See how a WIP Probot App works
    event: pull_request.edited
    link: {{ repoUrl }}/pull/1
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: test
        right: /\b(wip|do not merge|work in progress)\b/i # grabbed from https://github.com/wip/app/blob/59cbc474de03f32654c2a52cbd1d124f1dd2ac75/lib/handle-pull-request-change.js#L60-L62
        else:
          type: respond
          with: error-message.md
      - type: respond
        with: 02_intro-webhooks.md
        
  - title: Getting hooked with webhooks
    description: Understand what webhooks are and how they work
    event: pull_request.edited
    link: {{ repoUrl }}/pull/1
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: test
        right: /\b(wip|do not merge|work in progress)\b/i
        else:
          type: respond
          with: 02_intro-apis.md
     - type: respond
       with: error-message.md
       
  - title: APIs, at your service
    description: Understand the basic functions of an API
    event: pull_request.closed
    link: {{ repoUrl }}/pull/1
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
        else: 
          - type: respond
            with: error-message.md
      - type: createIssue
        title: Install Reminder Probot App
        body: 03_reminder-app-prompt.md
        action_id: new_issue
      - type: respond
        with: next-message.md
        data:
          url: '%actions.new_issue.data.html_url%'
     
  - title: Install Reminder Probot App
    description: Install another Probot App on your repository
    event: installation.created
    link: {{ repoUrl }}/issues/2
    actions:
      - type: respond
        with: 03_reminder-install-success.md
        
  - title: Trigger the correct webhook event
    description: See what happens when arbitrary webhooks are triggered
    event: issues.closed
    link: {{ repoUrl }}/issues/2
    actions:
      - type: octokit
        method: issues.edit
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        number: '%payload.issue.number%'
        state: open
      - type: respond
        with: 03_closing-statement.md
  
  - title: Prompt Reminder App Webhook
    description: Now that the reminder App is installed, it's time to prompt the correct webhook event
    event: issue_comment.created
    link: {{ repoUrl }}/issues/2
    actions:
      - type: gate
        left: '%payload.issue_comment%'
        operator: test
        right: \n\n\`/remind me [what] [when]\` # grabbed from https://github.com/probot/reminders/blob/master/lib/reminders.js#L29
        else:
          respond:
          with:error-message.md
      - type: respond
        with: 03_trasition-to-exit.md
      - type: createIssue
        title: Well done!
        body: 04_graceful-exit.md
        action_id: final_issue
        data:
          url: '%actions.final_issue.data.html_url%'
