title: Introduction to GitHub Apps
tagline: Get started with GitHub Apps in a flash
description: See how automation can improve your workflow and reduce friction with GitHub Apps
template:
  name: introduction-to-github-apps
  url: "https://github.com/githubtraining/introduction-to-github-apps-template.git"
  repo: introduction-to-github-apps-template
before:
  - type: createPullRequest
    title: Introduction to GitHub Apps
    head: intro-gh-apps
    body: 01_intro-gh-apps.md
steps:
  - title: Install your first GitHub App then assign yourself to the pull request
    description: Learn what a GitHub App is and how to install it
    event: "pull_request.assigned"
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: gate
        left: "%payload.assignee.login%"
        operator: "==="
        right: "%user.username%"
      - type: respond
        with: 01_wip-actions.md

  - title: Trigger the WIP app
    description: Once installed, learn how to interact with the app
    event: "pull_request.edited"
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: search
        right: WIP
        else:
          - type: respond
            with: 02_WIP-error-message.md
      - type: respond
        with: 01_defining-webhooks-apis.md

  - title: Remove WIP from the title
    description: Interact with the WIP app by removing WIP from the title
    event: pull_request.edited
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: !===
        right: '/WIP/g'
        - type: respond
          with: 02_WIP-error-message2.md
      - type: respond
        with: 01_merge-success.md


  - title: Merge the first pull request
    description: Merge the first pull request of the course
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
    - type: gate
      left: '%payload.pull_request.merged%'
      else:
      - type: respond
        with: 02_accidental-close.md
    - type: createPullRequest
      title: Practice makes perfect
      body: 02_request-info-app-prompt.md
      head: request-info
      action_id: new_pr
    - type: respond
      issue: 1
      with: 02_next-pull-request.md
      data:
        url: '%actions.new_pr.data.html_url%'


  - title: Install another GitHub App
    description: Install another GitHub App called "Request Info"
    event: installation.created
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: respond
        with: 02_request-info-install-success.md

  - title: Customize the response of the Request Info app
    description: Learn how to customize the apps default behavior
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: octokit
        method: pullRequests.getFiles
        owner: '%payload.repository.owner.login%'
        name: '%payload.repository.name%'
        number: '%payload.pull_request.number%'
        action_id: pr_files
      - type: gate
        left: '%actions.pr_files.data%'
        operator: includes
        right: 'filename:config.yml'
        else:
          - type: mergePullRequest
            pullRequest: 2
          - type: createIssue
            title: Congratulations!
            body: 03_graceful-exit.md
            action_id: last_issue
          - type: respond
            with: 02_change-config-success.md
            data:
              url: '%actions.last_issue.data.html_url%'
      - type: respond
        with: 03_make-file-changes.md
